routes/web.php
<?php

use App\Http\Controllers\EventoController;
use App\Http\Controllers\UsuarioController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.home');
});


Route::get('eventos', [EventoController::class, 'index'])->name('eventos.index');
Route::get('eventos/{evento}',[EventoController::class, 'show'])->name('eventos.show');
Route::get('eventos/crear', [EventoController::class, 'create'])->name('eventos.create')->middleware('auth');
Route::post('eventos/crear',[EventoController::class, 'store'])->name('eventos.store');

Route::get('usuarios', [UsuarioController::class, 'index'])->name('usuarios.index');
Route::get('usuarios/{usuario}', [UsuarioController::class, 'show'])->name('usuarios.show');
Route::get('usuarios/{usuario}/editar',[UsuarioController::class, 'edit'])->name('usuarios.edit')->middleware('auth');
Route::get('registro', [UsuarioController::class, 'create'])->name('usuarios.create')->middleware('auth');
Route::post('registro',[UsuarioController::class, 'store'])->name('usuarios.store');
Route::put('usuarios/{usuario}/editar',[UsuarioController::class, 'update'])->name('usuarios.update');
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Evento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Evento extends Model
{
    use HasFactory;

    protected $table = "eventos";


    public function getDias()
    {
        $fechaFormateada = Carbon::parse($this->fecha_creacion);
        return $fechaFormateada->diffInDays(Carbon::now());
    }

    protected $fillable = [
        'nombre',
        'fecha_creacion',
        'descripcion',
        'miembros'
    ];
    public function users() {
        return $this->belongsToMany('App\User');
    }
}

app/Models/Inscripcion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inscripcion extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
    public function eventos()
    {
        return  $this->hasMany('App\Evento');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EventoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Evento;
class EventoController extends Controller
{
    public function index(){ 
        $eventos = Evento::all();
        return view('eventos.index',['eventos'=>$eventos]);
        return view('eventos.index', compact('eventos'));

    }
    public function show($evento)
    {
       $e = Evento::findorFail($evento);
        return view('eventos.show', ['eventos'=>$e]);
        return view('eventos.show', compact('eventos'));
    }
    public function create(){
        return view('eventos.create');
    }
    public function store(Request $request) {
        $evento = new Evento();
        $evento->nombre= $request->nombre;
        $evento->fecha_creacion = now();
        $evento->descripción = $request->descripcion;
        $evento->miembros = 1;
        $evento->save();
        return redirect()->action([EventoController::class, 'index']);

    }
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UsuarioController extends Controller
{
    public function show($usuario)
    {
       $u = User::findorFail($usuario);
        return view('usuarios.show', ['usuarios'=>$u]);
        return view('usuarios.show', compact('usuarios'));
    }
    public function edit($usuario){
        $u = User::findorFail($usuario);
        return view("usuarios.edit",['usuarios'=>$u]);
        return view('usuarios.edit', compact('usuarios'));
    }
    public function index(){ 
        $users = User::all();
        return view('usuarios.index',['usuarios'=>$users]);
        return view('usuarios.index', compact('usuarios'));

    }
    public function create(){
        return view('usuarios.create');
    }
    public function store(Request $request) {
        $usuario = new User();
        $usuario->name= $request->name;
        $usuario->email = $request->email;
        $usuario->password = bcrypt($request->password);
        $usuario->created_at = now();
        $usuario->save();
        return redirect()->action([UsuarioController::class, 'index']);

    }
    public function update(Request $request, $id) {
        $usuario = User::find($id);
        $usuario->name= $request->name;
        $usuario->email = $request->email;
        $usuario->created_at = $request->created_at;
        $usuario->save();
        return redirect()->action([UsuarioController::class, 'index']);

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/eventos/create.blade.php
@extends('layouts.master')

@section('titulo')
    Crear evento
@endsection

@section("contenido")
<div class="row">
        <div class="offset-md-3 col-md-6">
            <div class="card">
                <div class="card-header text-center">Crear evento</div>
                <div class="card-body"
                     style="padding:30px">
                    <form action="{{route("eventos.store")}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="especie">Nombre:</label>
                            <input type="text" name="nombre" id="nombre" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="descripcion">Descripción:</label>
                            <textarea name="descripcion"
                                      id="descripcion"
                                      class="form-control"
                                      rows="3"></textarea>
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success" style="padding:8px 100px;margin-top:25px;">
                                Crear evento
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/eventos/index.blade.php
@extends('layouts.master')
@section('titulo')
Eventos
@endsection
@section('contenido')
<div class="row">
@foreach( $eventos as $clave => $evento )
<div class="card-group">
  <div class="card">
    <img class="card-img-top" src="{{asset('assets/imagenes/evento.png')}}" width="100px" height="100px" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><b><a href="{{ route('eventos.show' , $evento->id ) }}">{{$evento->nombre}}</a></b></h5>
      <p class="card-text">{{$evento->descripcion}}</p>
      <p class="card-text"><small class="text-muted">Fecha de Creación: {{$evento->fecha_creacion}}</small></p>
    </div>
@endforeach
</div>


@endsection

resources/views/eventos/show.blade.php
@extends('layouts.master')
@section('titulo')
Ver evento
@endsection
@section('contenido')
<div class="row">
<div class="col-sm-3"><br>
<figure class="figure">
  <img src="{{asset('assets/imagenes/evento.png')}}" class="figure-img img-fluid rounded">
</figure>
</div>
<div class="col-sm-9">
<p class="h1">{{$eventos->nombre}}</p>
<p class="h4">Fecha creación:</p>
<p class="lead">{{$eventos->fecha_creacion}}   (hace  {{$eventos->getDias()}} días)</p>
<p class="h4">Miembros::</p>
<p class="lead">{{$eventos->miembros}}</p>
<p class="h4">Descripción:</p>
<p class="lead">{{$eventos->descripcion}}</p>
</a>
<a href="{{route("eventos.index")}}"><button type="button" class="btn btn-dark">Volver a eventos</button></a>
<br>
</div>
</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <x-jet-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/home.blade.php
@extends('layouts.master')
@section('titulo')
Home
@endsection
@section('contenido')
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
    <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{asset('assets/imagenes/concierto.jpg')}}" width="500px" height="500px" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{asset('assets/imagenes/concierto2.jpg')}}" width="500px" height="500px" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{asset('assets/imagenes/concierto3.jpg')}}" width="500px" height="500px" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>
@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{{ url('/assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/layout.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,600">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css">
    <link rel="stylesheet" href="assets/css/media-queries.css">
    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{{ url('/assets/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="assets/js/jquery-3.2.1.min.js"></script>
    <script src="assets/js/jquery-migrate-3.0.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="assets/js/jquery.backstretch.min.js"></script>
    <script src="assets/js/wow.min.js"></script>
    <script src="assets/js/retina-1.1.0.min.js"></script>
    <script src="assets/js/scripts.js"></script>




    <title>musinoma</title>

</head>

<body>

    @include('layouts.partials.navbar')

    <div class="container-fluid">
        @yield('contenido')

    </div>

    @include('layouts.partials.footer')
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
</body>

</html>

resources/views/layouts/partials/footer.blade.php
        <footer>
        	<div class="footer-top">
		        <div class="container">
		        	<div class="row">
		        		<div class="col-md-3 footer-about wow fadeInUp">
		        			<h3>Sobre nosotros:</h3>
		        			<p>
		        				Somos una red social para amantes de la música.
		        			</p>
		        			<p>&copy; musinoma </p>
	                    </div>
		        		<div class="col-md-4 offset-md-1 footer-contact wow fadeInDown">
		        			<h3>Contacto</h3>
		                	<p><i class="fas fa-map-marker-alt"></i> Calle Prueba 10, 10136 Torrelavega Cantabria</p>
		                	<p><i class="fas fa-phone"></i> Telefono: 6569350177</p>
		                	<p><i class="fas fa-envelope"></i> Email: <a href="mailto:fernando.palaciogomez@iesmiguelherrero.com">fernando.palaciogomez@iesmiguelherrero.com</a></p>
		                	<p><i class="fab fa-skype"></i> Skype: Fernando</p>
	                    </div>
	                    <div class="col-md-4 footer-links wow fadeInUp">
	                    	<div class="row">
	                    		<div class="col">
	                    			<h3>Links</h3>
	                    		</div>
	                    	</div>
	                    	<div class="row">
	                    		<div class="col-md-6">
	                    			<p><a class="scroll-link" href="#top-content">Home</a></p>
	                    			<p><a href="#">Herramientas</a></p>
	                    			<p><a href="#">Funcionamiento</a></p>
	                    			<p><a href="#">Apartado clientes</a></p>
	                    		</div>
	                    		<div class="col-md-6">
	                    			<p><a href="#">Condiciones &amp; uso</a></p>
	                    			<p><a href="#">Afiliados</a></p>
	                    			<p><a href="#">Términos</a></p>
	                    		</div>
	                    	</div>
	                    </div>
		            </div>
		        </div>
	        </div>
	        <div class="footer-bottom">
	        	<div class="container">
	        		<div class="row">
	           			<div class="col footer-social">
	                    	<a href="#"><i class="fab fa-facebook-f"></i></a> 
							<a href="#"><i class="fab fa-twitter"></i></a> 
							<a href="#"><i class="fab fa-google-plus-g"></i></a> 
							<a href="#"><i class="fab fa-instagram"></i></a> 
							<a href="#"><i class="fab fa-pinterest"></i></a>
	                    </div>
	           		</div>
	        	</div>
	        </div>
        </footer>

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #000000;">
  <div class="container-fluid">
  <a class="navbar-brand" href="{{url('/')}}">musinoma</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      {{--@if(Auth::check() )--}}
      
      <li class="nav-item">
        <a href="{{route("usuarios.index")}}" class="nav-link" >Usuarios</a>
      </li>
      <li class="nav-item">
        <a href="{{route("eventos.index")}}" class="nav-link">Eventos</a>
      </li>
      <li class="nav-item">
        <a href="{{route("usuarios.create")}}" class="nav-link">Añadir Usuario</a>
      </li>
      <li class="nav-item">
        <a href="{{route("eventos.create")}}"  class="nav-link">Crear evento</a>
      </li>
      <li class="nav-item">
        <a href="{{url('register')}}" class="nav-link">Registrarse</a>
      </li>
    </ul>
    {{--@endif --}}
    @if(Auth::check() )
        <form class="d-flex">
          <input id="busqueda" class="form-control mr-sm-3" type="text" placeholder="Buscar" aria-label="Buscar">
        </form>
        
        <ul class="navbar-nav navbar-right">
          <li class="nav-item">
            <a href="{{ route('profile.show') }}"  class="nav-link">
              {{ Auth::user()->name }}
            </a>
          </li>
            <li class="nav-item">
                <a href="{{ route('logout') }}"  class="nav-link"
                  onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();" >
                    <span class="glyphicon glyphicon-off"></span>
                    Cerrar sesión
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    @else
        <ul class="navbar-nav navbar-right">
            <li class="nav-item">
              <a href="{{url('login')}}" class="nav-link">Login</a>
            </li>
        </ul>
    @endif 
  </div>
</div>
</nav>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/usuarios/create.blade.php
@extends('layouts.master')

@section('titulo')
    Registrar usuario
@endsection

@section("contenido")
    <form class="col" action="{{route("usuarios.store")}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col form-group">
                <label for="nombre">Nombre:</label>
                <input type="text" class="form-control" name="name" id="name" aria-describedby="helpId"
                       placeholder="Introduzca un nombre">
            </div><br>
            <div class="col form-group">
                <label for="nombre">Email:</label>
                <input type="text" class="form-control" name="email" id="email" aria-describedby="helpId"
                       placeholder="Introduzca un email">
            </div><br>
            <div class="col form-group">
                <label for="nombre">Contraseña:</label>
                <input type="text" class="form-control" name="password" id="password" aria-describedby="helpId"
                       placeholder="Introduzca una contraseña">
            </div>
            
        <button type="submit" name="submit" class="row btn btn-primary">Registrarse</button>
    </form>
@endsection

resources/views/usuarios/edit.blade.php
@extends("layouts.master")

@section("titulo")
    Editar usuario
@endsection

@section("contenido")
    <div class="row">
        <div class="offset-md-3 col-md-6">
            <div class="card">
                <div class="card-header text-center">Editar usuario {{$usuarios->name}}</div>
                <div class="card-body"
                     style="padding:30px">
                    <form action="{{route("usuarios.update", $usuarios)}}" method="post" enctype="multipart/form-data">
                    @method("put")
                        @csrf
                        <div class="form-group">
                            <label for="name">Nombre</label>
                            <input type="text" name="name" id="name" class="form-control" required
                                   value="{{$usuarios->name}}">
                        </div>
                        <div class="form-group">
                            <label for="peso">Email: </label>
                            <input type="email" class="form-control" name="email" value="{{$usuarios->email}}"
                                   required>
                        </div>
                        
                        <div class="form-group">
                            <label for="fechaNacimiento">Fecha de registro: </label>
                            <input type="date" class="form-control" name="created_at"
                                   value="{{$usuarios->created_at}}"
                                   required>
                        </div>
                        
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success" style="padding:8px 100px;margin-top:25px;">
                                Editar
                                usuario
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.master')
@section('titulo')
Usuarios
@endsection
@section('contenido')

<br><br>
<div class="row">
@foreach( $usuarios as $clave => $usuario )
<div class="card" style="width:400px">
  <img class="card-img-top" src="{{asset('assets/imagenes/usuario.png')}}" alt="Card image">
  <div class="card-body">
    <h4 class="card-title">{{$usuario->name}}</h4>
    <p class="card-text">{{$usuario->email}}</p>
    <a href="{{ route('usuarios.show' , $usuario->id ) }}" class="btn btn-primary">Ver perfil</a>
  </div>
</div>
@endforeach
</div>

@endsection

resources/views/usuarios/show.blade.php
@extends('layouts.master')
@section('titulo')
Ver perfil
@endsection
@section('contenido')
<div class="row">
<div class="col-sm-3"><br>
<figure class="figure">
  <img src="{{asset('assets/imagenes/usuario.png')}}" class="figure-img img-fluid rounded">
</figure>
</div>
<div class="col-sm-9">
<p class="h1">{{$usuarios->name}}</p>
<p class="h4">Email:</p>
<p class="lead">{{$usuarios->email}}</p>
<p class="h4">Fecha de Registro:</p>
<p class="lead">{{$usuarios->created_at}}</p>
<p class="h4">Descripción:</p>
<p class="lead">Este es un usuario de nuestra web.</p>
<a href="{{route("usuarios.edit", $usuarios->id)}}"><button type="button" class="btn btn-secondary">Editar usuario</button>
</a>
<a href="{{route("usuarios.index")}}"><button type="button" class="btn btn-dark">Volver a usuarios</button></a>
<br>
</div>
</div>

@endsection